# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [12.19.0]
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm packages
      run: npm install

    - name: Run tests
      run: npm run ci
    
    - name: Publish result
      uses: tanmen/jest-reporter@v1
      if: always()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-file: test_result.json
